// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACo3kQqxbP-RndrKGC0aiF-CCH_7p8TJ4',
    appId: '1:836998719172:web:b965a4b4fe6964b0eb8b91',
    messagingSenderId: '836998719172',
    projectId: 'zoemoeremans-notes',
    authDomain: 'zoemoeremans-notes.firebaseapp.com',
    storageBucket: 'zoemoeremans-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7nVW_Pub_7ULw4EJxu_sEV8MEMHguBLQ',
    appId: '1:836998719172:android:042d42cbd4af6776eb8b91',
    messagingSenderId: '836998719172',
    projectId: 'zoemoeremans-notes',
    storageBucket: 'zoemoeremans-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAe50_0Csbowm26dSZwgf-70TKcHKITGA',
    appId: '1:836998719172:ios:35571b167605a7b4eb8b91',
    messagingSenderId: '836998719172',
    projectId: 'zoemoeremans-notes',
    storageBucket: 'zoemoeremans-notes.appspot.com',
    iosBundleId: 'com.zoemoeremans.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAe50_0Csbowm26dSZwgf-70TKcHKITGA',
    appId: '1:836998719172:ios:35571b167605a7b4eb8b91',
    messagingSenderId: '836998719172',
    projectId: 'zoemoeremans-notes',
    storageBucket: 'zoemoeremans-notes.appspot.com',
    iosBundleId: 'com.zoemoeremans.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACo3kQqxbP-RndrKGC0aiF-CCH_7p8TJ4',
    appId: '1:836998719172:web:c19ffc92aee758f4eb8b91',
    messagingSenderId: '836998719172',
    projectId: 'zoemoeremans-notes',
    authDomain: 'zoemoeremans-notes.firebaseapp.com',
    storageBucket: 'zoemoeremans-notes.appspot.com',
  );

}